puts "🌱 Seeding spices..."

# Seed your database here
Series.create(title: "Pokemon")
Series.create(title: "Legend of Zelda")
Series.create(title: "Super Mario")

Game.create(title: "Pokemon Red", main_character: "Red", year_released: 1998, console: "GAME BOY", series_id: 1)
Game.create(title: "Pokemon Gold", main_character: "Gold", year_released: 1999, console: "GAME BOY Color", series_id: 1)
Game.create(title: "Pokemon Ruby", main_character: "Brendan", year_released: 2002, console: "GAME BOY ADVANCE", series_id: 1)
Game.create(title: "Pokemon Diamond", main_character: "Lucas", year_released: 2006, console: "Nintendo DS", series_id: 1)
Game.create(title: "Pokemon Black", main_character: "Hilbert", year_released: 2010, console: "Nintendo DS", series_id: 1)
Game.create(title: "Pokemon X", main_character: "Calem", year_released: 2013, console: "Nintendo 3DS", series_id: 1)
Game.create(title: "Pokemon Sun", main_character: "Elio", year_released: 2016, console: "Nintendo 3DS", series_id: 1)
Game.create(title: "Pokemon Sword", main_character: "Victor", year_released: 2019, console: "Nintendo Switch", series_id: 1)

Game.create(title: "Legend of Zelda", main_character: "Link", year_released: 1986, console: "NES", series_id: 2)
Game.create(title: "The Adventure of Link", main_character: "Link", year_released: 1987, console: "NES", series_id: 2)
Game.create(title: "A Link To The Past", main_character: "Link", year_released: 1991, console: "SNES", series_id: 2)
Game.create(title: "Link's Awakening", main_character: "Link", year_released: 1993, console: "GAME BOY", series_id: 2)
Game.create(title: "Ocarina of Time", main_character: "Link", year_released: 1998, console: "N64", series_id: 2)
Game.create(title: "Majora's Mask", main_character: "Link", year_released: 2000, console: "NES", series_id: 2)
Game.create(title: "Oracle of Seasons", main_character: "Link", year_released: 2001, console: "Game BOY Color", series_id: 2)
Game.create(title: "Wind Waker", main_character: "Link", year_released: 2002, console: "GAMECUBE", series_id: 2)
Game.create(title: "Four Swords Adventure", main_character: "Link", year_released: 2004, console: "GAMECUBE", series_id: 2)
Game.create(title: "The Minish Cap", main_character: "Link", year_released: 2004, console: "GAME BOY ADVANCE", series_id: 2)
Game.create(title: "Twilight Princess", main_character: "Link", year_released: 2006, console: "Wii", series_id: 2)
Game.create(title: "Phantom Hourglass", main_character: "Link", year_released: 2007, console: "Nintendo DS", series_id: 2)
Game.create(title: "Spirit Trcks", main_character: "Link", year_released: 2009, console: "Nintendo DS", series_id: 2)
Game.create(title: "Skyward Sword", main_character: "Link", year_released: 2011, console: "Wii", series_id: 2)
Game.create(title: "A Link Between Worlds", main_character: "Link", year_released: 2013, console: "Nintendo 3DS", series_id: 2)
Game.create(title: "Tri Force Heroes", main_character: "Link", year_released: 2015, console: "Nintendo 3DS", series_id: 2)
Game.create(title: "Breath of The Wild", main_character: "Link", year_released: 2017, console: "Nintendo Switch", series_id: 2)

Game.create(title: "Super Mario Bros", main_character: "Mario", year_released: 1986, console: "NES", series_id: 3)
Game.create(title: "Super Mario Bros 2", main_character: "Mario", year_released: 1988, console: "NES", series_id: 3)
Game.create(title: "Super Mario Bros 3", main_character: "Mario", year_released: 1990, console: "NES", series_id: 3)
Game.create(title: "Super Mario World", main_character: "Mario", year_released: 1991, console: "SNES", series_id: 3)
Game.create(title: "Super Mario 64", main_character: "Mario", year_released: 1996, console: "N64", series_id: 3)
Game.create(title: "Super Mario Sunshine", main_character: "Mario", year_released: 2002, console: "GAMECUBE", series_id: 3)
Game.create(title: "New Super Mario Bros", main_character: "Mario", year_released: 2006, console: "Nintendo DS", series_id: 3)
Game.create(title: "Super Mario Galaxy", main_character: "Mario", year_released: 2007, console: "Wii", series_id: 3)
Game.create(title: "New Super Mario Bros Wii", main_character: "Mario", year_released: 2009, console: "Wii", series_id: 3)
Game.create(title: "Super Mario Galaxy 2", main_character: "Mario", year_released: 2010, console: "Wii", series_id: 3)
Game.create(title: "Super Mario 3D Land", main_character: "Mario", year_released: 2011, console: "Nintendo 3DS", series_id: 3)
Game.create(title: "New Super Mario Bros 2", main_character: "Mario", year_released: 2012, console: "Nintendo 3DS", series_id: 3)
Game.create(title: "New Super Mario Bros U", main_character: "Mario", year_released: 2012, console: "Wii U", series_id: 3)
Game.create(title: "Super Mario 3D World", main_character: "Mario", year_released: 2013, console: "Wii U", series_id: 3)
Game.create(title: "Super Mario Maker", main_character: "Mario", year_released: 2015, console: "Wii U", series_id: 3)
Game.create(title: "Super Mario Odyssey", main_character: "Mario", year_released: 2017, console: "Nintendo Switch", series_id: 3)
Game.create(title: "Super Mario Maker 2", main_character: "Mario", year_released: 2019, console: "Nintendo Switch", series_id: 3)
puts "✅ Done seeding!"
